version: 2

before:
  hooks:
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run ./cmd/mlp completion bash > completions/mlp.bash'
    - sh -c 'go run ./cmd/mlp completion zsh > completions/_mlp'
    - sh -c 'go run ./cmd/mlp completion fish > completions/mlp.fish'
    - rm -rf man
    - sh -c 'go run ./cmd/mlp gendoc man'

builds:
  - id: mlp
    main: ./cmd/mlp
    binary: mlp
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: mlp
    formats: [tar.gz]
    files:
      - LICENSE
      - completions/*
      - man/*
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  format: "{{ .Message }}"
